export const pages = [
    "attributions",
    "contribution",
    "description",
    "engineering",
    "experiments",
    "home",
    "human-practices",
    "notebook",
    "results",
    "safety",
    "members",
    "education",
    "entrepreneurship",
    "hardware",
    "inclusivity",
    "measurement",
    "model",
    "plant",
    "software",
    "sustainability",
  ];
  